version: '3.8'

services:
  chihaya:
    image: chihaya/chihaya # 使用之前构建的 Docker 镜像
    container_name: chihaya_tracker
    ports:
      - "6881:6881" # 将容器的 6881 端口映射到主机的 6881 端口
    volumes:
      - ./config.yaml:/etc/chihaya/config.yaml # 挂载配置文件
    restart: always # 容器退出时总是重启
